{"context": "`Using TensorFlow backend.\nTraceback (most recent call last):\n  File \"mnist-cnn.py\", line 14, in \n    from keras.utils.visualize_util import plot\n  File \"/usr/local/lib/python2.7/dist-packages/keras/utils/visualize_util.py\", line 13, in \n    raise RuntimeError('Failed to import pydot. You must install pydot'\n\nRuntimeError: Failed to import pydot. You must install pydot and graphviz for pydotprint to work.`\n\n\u4e0a\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u6642\nsudo apt-get install graphviz\npip install graphviz\npip install pydot==1.1.0\n\u3092\u884c\u3063\u305f\u3002\non Ubuntu 16.04.\n`Using TensorFlow backend.\nTraceback (most recent call last):\n  File \"mnist-cnn.py\", line 14, in <module>\n    from keras.utils.visualize_util import plot\n  File \"/usr/local/lib/python2.7/dist-packages/keras/utils/visualize_util.py\", line 13, in <module>\n    raise RuntimeError('Failed to import pydot. You must install pydot'\n###<b>RuntimeError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.</b>`\n\n#\u4e0a\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u6642\n\nsudo apt-get install graphviz\npip install graphviz\npip install pydot==1.1.0\n\u3092\u884c\u3063\u305f\u3002\n\non Ubuntu 16.04.\n", "tags": ["Python", "TensorFlow", "Keras"]}