{"context": " More than 1 year has passed since last update.\n\n\u73fe\u8c61\n\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3002\nStarted GET \"/users/auth/facebook/callback?redirect_uri=REDIRECT_URL&code=CODE&state=STATE\" for ::1 at 2015-11-28 14:14:54 +0900\nI, [2015-11-28T14:14:54.941266 #9383]  INFO -- omniauth: (facebook) Callback phase initiated.\nE, [2015-11-28T14:14:56.362811 #9383] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, :\n{\"error\":{\"message\":\"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"FACEBOOK_ID\"}}\nProcessing by Users::OmniauthCallbacksController#failure as HTML\n  Parameters: {\"redirect_uri\"=>\"http://localhost:3000//\", \"code\"=>\"CODE\", \"state\"=>\"STATE\"}\nRedirected to http://localhost:3000/users/sign_in\nCompleted 302 Found in 88ms (ActiveRecord: 0.0ms)\n\n\n\u5bfe\u7b56\ndevise\u306ewiki\u3092\u898b\u308b\u3068\nNote: v2.0.1 has an issue with callback url error. You need to add a callback url on config.\nconfig.omniauth :facebook, \"APP_ID\", \"APP_SECRET\",\n                callback_url: \"CALLBACK_URL\"\n\n\u30d0\u30fc\u30b8\u30e7\u30f3\u56fa\u6709\u306e\u554f\u984c\u304b\u3082\u3057\u308c\u306a\u3044\u3002\nomniauth-facebook\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u307f\u308b\u3068\nomniauth-facebook (2.0.1)\n\n\u30d0\u30fc\u30b8\u30e7\u30f3\u306b\u3053\u3060\u308f\u308a\u306f\u306a\u304b\u3063\u305f\u306e\u3067\u3001\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u4e0a\u3052\u3066\u3057\u307e\u3046\u3053\u3068\u306b\u3059\u308b\u3002\nbundle update omniauth-facebook\n\n\u89e3\u6c7a\u3057\u305f\u3002\n## \u73fe\u8c61\n\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3002\n\n```\nStarted GET \"/users/auth/facebook/callback?redirect_uri=REDIRECT_URL&code=CODE&state=STATE\" for ::1 at 2015-11-28 14:14:54 +0900\nI, [2015-11-28T14:14:54.941266 #9383]  INFO -- omniauth: (facebook) Callback phase initiated.\nE, [2015-11-28T14:14:56.362811 #9383] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, :\n{\"error\":{\"message\":\"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"FACEBOOK_ID\"}}\nProcessing by Users::OmniauthCallbacksController#failure as HTML\n  Parameters: {\"redirect_uri\"=>\"http://localhost:3000//\", \"code\"=>\"CODE\", \"state\"=>\"STATE\"}\nRedirected to http://localhost:3000/users/sign_in\nCompleted 302 Found in 88ms (ActiveRecord: 0.0ms)\n```\n\n## \u5bfe\u7b56\n[devise\u306ewiki](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#facebook-example)\u3092\u898b\u308b\u3068\n\nNote: v2.0.1 has an issue with callback url error. You need to add a callback url on config.\n\n``` rb\nconfig.omniauth :facebook, \"APP_ID\", \"APP_SECRET\",\n                callback_url: \"CALLBACK_URL\"\n```\n\n\u30d0\u30fc\u30b8\u30e7\u30f3\u56fa\u6709\u306e\u554f\u984c\u304b\u3082\u3057\u308c\u306a\u3044\u3002\nomniauth-facebook\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u307f\u308b\u3068\n\n``` rb\nomniauth-facebook (2.0.1)\n```\n\n\u30d0\u30fc\u30b8\u30e7\u30f3\u306b\u3053\u3060\u308f\u308a\u306f\u306a\u304b\u3063\u305f\u306e\u3067\u3001\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u4e0a\u3052\u3066\u3057\u307e\u3046\u3053\u3068\u306b\u3059\u308b\u3002\n\n```\nbundle update omniauth-facebook\n```\n\n\u89e3\u6c7a\u3057\u305f\u3002\n", "tags": ["devise", "Rails", "omniauth-facebook"]}