{"context": "\n\n\u3010 \u53c2\u8003 \u3011\n\n\nryskchy\u3055\u3093 Qiita\u8a18\u4e8b \u300cpandas\u306eMultiIndex\u306b\u3064\u3044\u3066\u300d\n\n\n\ncsv\u30d5\u30a1\u30a4\u30eb \u306e \u4e2d\u8eab\n\nDate,Name,Dept,Age,Location  \n2015/02/03,'Ken Rodgers','Marketing',52,'Mexico'\n2015/05/02,'Tommy Tomioka','Accounting','Brazil'\n2015/04/01,'Shinguji Sakura','Teikoku Kagekidan', 'Tokyo'\n\n\n\n\n\u884c\u540d\u30e9\u30d9\u30eb\uff08index\uff09\u3068\u3057\u3066\u3001\u8907\u6570\u5217 \u3092 \u6307\u5b9a\u3059\u308b\u3002\n\n\nPython 3.5.2\n>>> sample_df = pd.read_csv(\"sample.csv\", sep=\",\", index_col =['Name', 'Dept'])\n>>> sample_df\n\nName              Dept  Date  Age  Location                                         \n'Ken Rodgers'     'Marketing'          2015/02/03   52  'Mexico'\n'Tommy Tomioka'   'Accounting'         2015/05/02   29  'Brazil'\n'Shinguji Sakura' 'Teikoku Kagekidan'  2015/04/01   17   'Tokyo'\n>>>\n\n\n\nPython 3.5.2\n>>> sample_df.index\nMultiIndex(levels=[[''Ken Rodgers'', ''Shinguji Sakura'', ''Tommy Tomioka''], [''Accounting'', ''Marketing'', ''Teikoku Kagekidan'']],\n           labels=[[0, 2, 1], [1, 0, 2]],\n           names=['Name', 'Dept'])\n>>> \n\n\n\n\uff12\u3064\u306e\u5024 \u304c\u3001\u30ea\u30ec\u30fc\u30b7\u30e7\u30ca\u30eb\u30fb\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9 \u3067 \u3044\u3046\u3068\u3053\u308d \u306e\u300c\u8907\u5408\u30d7\u30e9\u30a4\u30de\u30ea\u30fb\u30ad\u30fc\u300d\uff08\u8907\u5408\u4e3b\u30ad\u30fc\uff09\u3092 \u69cb\u6210 \u3057\u3066\u3044\u308b\u3002\n\n\nPython 3.5.2\n>>> list(sample_df.index)\n[(\"'Ken Rodgers'\", \"'Marketing'\"), (\"'Tommy Tomioka'\", \"'Accounting'\"), (\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\n>>>\n\n\n\n\u884c\u30e9\u30d9\u30eb\uff08 Index \uff09\u306b\u6307\u5b9a\u3057\u305f\u5217\u540d \u306f\u3001\u3082\u306f\u3084\u3001\u30ab\u30e9\u30e0\u540d \u3068\u3057\u3066 \u306f \u8a8d\u8b58\u3055\u308c\u306a\u3044\n\n\nPython 3.5.2\n>>> sample_df.columns\nIndex(['Date', 'Age', 'Location'], dtype='object')\n>>> \n>>> list(sample_df.columns)\n['Date', 'Age', 'Location']\n>>> \n\n\n\n\u300c\u8907\u5408\u4e3b\u30ad\u30fc\u300d\u306e \u3088\u3046\u306b\u3001\u884c\u30e9\u30d9\u30eb \u3092 \u6307\u5b9a\u3059\u308b\u3068\u3001\u305d\u306e\u884c\u30e9\u30d9\u30eb \u3092 \u6301\u3064 \u884c \u304c \u53d6\u308a\u51fa\u3055\u308c\u308b\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Tommy Tomioka'\", \"'Accounting'\")]\nDate        2015/05/02\nAge                 29\nLocation      'Brazil'\nName: ('Tommy Tomioka', 'Accounting'), dtype: object\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\nDate        2015/04/01\nAge                 17\nLocation       'Tokyo'\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>>\n\n\n\n\u3055\u3089\u306b\u5217 \u3082 \u6307\u5b9a\u3067\u304d\u308b\u3002\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Age']\n17\n>>> \n\n\n\n\u5217 \u3092 \u8907\u6570\u3001\u6307\u5b9a\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Date')]\nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n\n\u5217\u306f\u3001\u9264\u62ec\u5f27\u3067\u304f\u304f\u3063\u3066\u3082\u826f\u3044\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ['Age', 'Date']] \nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Date')]\nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n\nindex\u306f\u3001\u4e38\u62ec\u5f27\u3067\u306a\u3044\u3068\u30a8\u30e9\u30fc\n\n\nPython 3.5.2\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"], ['Age', 'Date']] \nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"], ('Age', 'Date')]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"]]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1296, in __getitem__\n    return self._getitem_axis(key, axis=0)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n\n\n\nindex \u306f \u4e38\u62ec\u5f27 \u306a\u3089 OK\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\nDate        2015/04/01\nAge                 17\nLocation       'Tokyo'\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n\n\u9593\u9055\u3063\u3066\u3001index\u3068\u3057\u3066\u6271\u308f\u308c\u3066\u3044\u308b\u5217\u540d \u3092 \u5217\u6307\u5b9a\u3059\u308b\u3068\u3001NaN \u304c \u8fd4\u3055\u308c\u308b\u3002\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Location', 'Dept')] \nLocation    'Tokyo'\nDept            NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n\n\n\u5b58\u5728\u3057\u306a\u3044\uff08\u672a\u5b9a\u7fa9\uff09\u5217\u540d \u3092 \u5358\u72ec \u3067 \u5217\u6307\u5b9a \u3059\u308b \u3068\u30a8\u30e9\u30fc \u306b \u306a\u308b\n\uff08 'Dept' \u306f\u3001\u884c\u30e9\u30d9\u30eb\u540d\uff08 Index \uff09 \u306b\u8a2d\u5b9a\u3055\u308c\u3066\u3044\u308b\u306e\u3067\u3001\u5217\u540d\u3068\u3057\u3066 \u306f \u3082\u306f\u3084\u3001 \u5b58\u5728\u3057\u306a\u3044 \uff09\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Dept']\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Dept')]\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Name']\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Name] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Name] is not in the [index]'\n>>> \n\n\n\n\uff11\u500b \u3067\u3082 \u5b58\u5728\u3059\u308b\uff08\u5b9a\u7fa9\u6e08\u307f\u3067\u3042\u308b\uff09\u5217\u540d \u3092 \u6307\u5b9a\u3059\u308b \u3068 OK\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Name')]\nAge      17\nName    NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n\nPython 3.5.2\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Location', 'Age', 'Names')]\nLocation    'Tokyo'\nAge              17\nNames           NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n\n\n###__\u3010 \u53c2\u8003 \u3011__\n\n* [ryskchy\u3055\u3093 Qiita\u8a18\u4e8b \u300cpandas\u306eMultiIndex\u306b\u3064\u3044\u3066\u300d](http://qiita.com/ryskchy/items/59028f1a3ed1d433b1a8)\n\n___\n\n\n####__csv\u30d5\u30a1\u30a4\u30eb \u306e \u4e2d\u8eab__\n\n```\nDate,Name,Dept,Age,Location  \n2015/02/03,'Ken Rodgers','Marketing',52,'Mexico'\n2015/05/02,'Tommy Tomioka','Accounting','Brazil'\n2015/04/01,'Shinguji Sakura','Teikoku Kagekidan', 'Tokyo'\n```\n\n<img width=\"1068\" alt=\"\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8 2017-02-13 19.40.04.png\" src=\"https://qiita-image-store.s3.amazonaws.com/0/43487/7f93089b-9b68-8607-c586-e4d11ed0282d.png\">\n\n<img width=\"941\" alt=\"\u30b9\u30af\u30ea\u30fc\u30f3\u30b7\u30e7\u30c3\u30c8 2017-02-13 19.27.31.png\" src=\"https://qiita-image-store.s3.amazonaws.com/0/43487/66f74eba-369f-5049-a95a-fc5c63e70cc9.png\">\n\n\n####__\u884c\u540d\u30e9\u30d9\u30eb\uff08index\uff09\u3068\u3057\u3066\u3001\u8907\u6570\u5217 \u3092 \u6307\u5b9a\u3059\u308b\u3002__\n\n```{python:Python 3.5.2}\n>>> sample_df = pd.read_csv(\"sample.csv\", sep=\",\", index_col =['Name', 'Dept'])\n>>> sample_df\n\nName              Dept  Date  Age  Location                                         \n'Ken Rodgers'     'Marketing'          2015/02/03   52  'Mexico'\n'Tommy Tomioka'   'Accounting'         2015/05/02   29  'Brazil'\n'Shinguji Sakura' 'Teikoku Kagekidan'  2015/04/01   17   'Tokyo'\n>>>\n```\n\n\n```{python:Python 3.5.2}\n>>> sample_df.index\nMultiIndex(levels=[[''Ken Rodgers'', ''Shinguji Sakura'', ''Tommy Tomioka''], [''Accounting'', ''Marketing'', ''Teikoku Kagekidan'']],\n           labels=[[0, 2, 1], [1, 0, 2]],\n           names=['Name', 'Dept'])\n>>> \n```\n\n####__\uff12\u3064\u306e\u5024 \u304c\u3001\u30ea\u30ec\u30fc\u30b7\u30e7\u30ca\u30eb\u30fb\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9 \u3067 \u3044\u3046\u3068\u3053\u308d \u306e\u300c\u8907\u5408\u30d7\u30e9\u30a4\u30de\u30ea\u30fb\u30ad\u30fc\u300d\uff08\u8907\u5408\u4e3b\u30ad\u30fc\uff09\u3092 \u69cb\u6210 \u3057\u3066\u3044\u308b\u3002__\n\n```{python:Python 3.5.2}\n>>> list(sample_df.index)\n[(\"'Ken Rodgers'\", \"'Marketing'\"), (\"'Tommy Tomioka'\", \"'Accounting'\"), (\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\n>>>\n```\n\n* __\u884c\u30e9\u30d9\u30eb\uff08 *Index* \uff09\u306b\u6307\u5b9a\u3057\u305f\u5217\u540d \u306f\u3001\u3082\u306f\u3084\u3001\u30ab\u30e9\u30e0\u540d \u3068\u3057\u3066 \u306f \u8a8d\u8b58\u3055\u308c\u306a\u3044__\n\n```{python:Python 3.5.2}\n>>> sample_df.columns\nIndex(['Date', 'Age', 'Location'], dtype='object')\n>>> \n>>> list(sample_df.columns)\n['Date', 'Age', 'Location']\n>>> \n```\n\n* __\u300c\u8907\u5408\u4e3b\u30ad\u30fc\u300d\u306e \u3088\u3046\u306b\u3001\u884c\u30e9\u30d9\u30eb \u3092 \u6307\u5b9a\u3059\u308b\u3068\u3001\u305d\u306e\u884c\u30e9\u30d9\u30eb \u3092 \u6301\u3064 \u884c \u304c \u53d6\u308a\u51fa\u3055\u308c\u308b__\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Tommy Tomioka'\", \"'Accounting'\")]\nDate        2015/05/02\nAge                 29\nLocation      'Brazil'\nName: ('Tommy Tomioka', 'Accounting'), dtype: object\n>>> \n```\n\n```{python:Python 3.5.2} \n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\nDate        2015/04/01\nAge                 17\nLocation       'Tokyo'\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>>\n```\n\n* __\u3055\u3089\u306b\u5217 \u3082 \u6307\u5b9a\u3067\u304d\u308b\u3002__\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Age']\n17\n>>> \n```\n\n* __\u5217 \u3092 \u8907\u6570\u3001\u6307\u5b9a__\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Date')]\nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n\n* \u5217\u306f\u3001\u9264\u62ec\u5f27\u3067\u304f\u304f\u3063\u3066\u3082\u826f\u3044\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ['Age', 'Date']] \nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Date')]\nAge             17\nDate    2015/04/01\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n\n* index\u306f\u3001\u4e38\u62ec\u5f27\u3067\u306a\u3044\u3068\u30a8\u30e9\u30fc\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"], ['Age', 'Date']] \nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n```\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"], ('Age', 'Date')]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n```\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[[\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"]]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1296, in __getitem__\n    return self._getitem_axis(key, axis=0)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1460, in _getitem_axis\n    locs = labels.get_locs(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/indexes/multi.py\", line 1838, in get_locs\n    '({1})'.format(len(tup), self.lexsort_depth))\nKeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (1), lexsort depth (0)'\n>>> \n```\n\n* __index \u306f \u4e38\u62ec\u5f27 \u306a\u3089 OK__\n\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\")]\nDate        2015/04/01\nAge                 17\nLocation       'Tokyo'\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n\n* __\u9593\u9055\u3063\u3066\u3001index\u3068\u3057\u3066\u6271\u308f\u308c\u3066\u3044\u308b\u5217\u540d \u3092 \u5217\u6307\u5b9a\u3059\u308b\u3068\u3001NaN \u304c \u8fd4\u3055\u308c\u308b\u3002__\n\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Location', 'Dept')] \nLocation    'Tokyo'\nDept            NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n\n* __\u5b58\u5728\u3057\u306a\u3044\uff08\u672a\u5b9a\u7fa9\uff09\u5217\u540d \u3092 \u5358\u72ec \u3067 \u5217\u6307\u5b9a \u3059\u308b \u3068\u30a8\u30e9\u30fc \u306b \u306a\u308b__\n\uff08 *'Dept'* \u306f\u3001\u884c\u30e9\u30d9\u30eb\u540d\uff08 *Index* \uff09 \u306b\u8a2d\u5b9a\u3055\u308c\u3066\u3044\u308b\u306e\u3067\u3001\u5217\u540d\u3068\u3057\u3066 \u306f \u3082\u306f\u3084\u3001 \u5b58\u5728\u3057\u306a\u3044 \uff09\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Dept']\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n>>> \n```\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Dept')]\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Dept] is not in the [index]'\n>>> \n```\n\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), 'Name']\nTraceback (most recent call last):\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1395, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Name] is not in the [index]'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1294, in __getitem__\n    return self._getitem_tuple(key)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 784, in _getitem_tuple\n    return self._getitem_lowerdim(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 891, in _getitem_lowerdim\n    return self._getitem_nested_tuple(tup)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 964, in _getitem_nested_tuple\n    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1466, in _getitem_axis\n    self._has_valid_type(key, axis)\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1403, in _has_valid_type\n    error()\n  File \"/Users/hirofumiyashima/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/indexing.py\", line 1390, in error\n    (key, self.obj._get_axis_name(axis)))\nKeyError: 'the label [Name] is not in the [index]'\n>>> \n```\n\n* __\uff11\u500b \u3067\u3082 \u5b58\u5728\u3059\u308b\uff08\u5b9a\u7fa9\u6e08\u307f\u3067\u3042\u308b\uff09\u5217\u540d \u3092 \u6307\u5b9a\u3059\u308b \u3068 OK__\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Age', 'Name')]\nAge      17\nName    NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n\n```{python:Python 3.5.2}\n>>> sample_df.loc[(\"'Shinguji Sakura'\", \"'Teikoku Kagekidan'\"), ('Location', 'Age', 'Names')]\nLocation    'Tokyo'\nAge              17\nNames           NaN\nName: ('Shinguji Sakura', 'Teikoku Kagekidan'), dtype: object\n>>> \n```\n", "tags": ["Python", "python3", "pandas", "DataFrame", "\u30c7\u30fc\u30bf\u5206\u6790"]}