{"context": "\u8272\u3005\u4e2d\u9014\u534a\u7aef\u306b\u3057\u3066\u308b\u306e\u306b\u3001\u65b0\u3057\u3044\u3053\u3068\u3092\u59cb\u3081\u308b\u306e\u3082\u3069\u3046\u304b\u3068\u601d\u304a\u3046\u304c\u3001Django\u3068TDD\u304c\u540c\u6642\u306b\u52c9\u5f37\u3067\u304d\u308b\u304a\u5f97\u306a\u672c\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u5b9f\u969b\u306b\u3084\u3063\u3066\u307f\u308b\u3053\u3068\u306b\u3057\u305f\u3002\nTest-Driven Development with Python\nCloudn\u306b\u65b0\u3057\u3044Ubuntu\u306evm\u3092\u7acb\u3063\u3066\u3002\n\u74b0\u5883\u3092\u6e96\u5099\u3002\n$ sudo apt-get update\n\n$ sudo apt-get upgrade\n\n$ sudo apt install python3-venv python3-pip\n\n$ pip install -U selenium\n\n$ vim functional_tests.py\n\nfrom selenium import webdriver\n\nbrowser = webdriver.Firefox()\nbrowser.get('http://localhost:8000')\n\nassert 'Django' in browser.title\n\n\u6700\u521d\u306e\u30c6\u30b9\u30c8 functional_tests.py\u3092\u5b9f\u884c\u3057\u305f\u3002\n\u672c\u3060\u3068\u6b21\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u306b\u306a\u308b\u306f\u305a\u3060\u304c\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 6, in <module>\n    assert 'Django' in browser.title\nAssertionError\n\n\u5b9f\u969b\u306e\u30a8\u30e9\u30fc\u306f\u3053\u3093\u306a\u611f\u3058\u3001\u3044\u304d\u306a\u308a\u672c\u306e\u5185\u5bb9\u3068\u9055\u3046\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3002\nX\u304c\u5165\u3063\u3066\u3044\u306a\u3044\u304b\u3089\u5f53\u7136\u304b\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 3, in <module>\n    browser = webdriver.Firefox()\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py\", line 80, in __init__\n    self.binary, timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 52, in __init__\n    self.binary.launch_browser(self.profile, timeout=timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 68, in launch_browser\n    self._wait_until_connectable(timeout=timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 99, in _wait_until_connectable\n    \"The browser appears to have exited \"\nselenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.\n\n\u89e3\u6c7a\u3059\u308b\u305f\u3081\u306bXvfb \u3068 pyvirtualdisplay\u3000\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n$ sudo apt-get install xvfb\n$ sudo pip install pyvirtualdisplay\n\n\u3055\u3089\u306b\u3001\u4eca\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306e\u3060\u3068\u30a8\u30e9\u30fc\u306b\u306a\u308b\u3088\u3046\u306a\u306e\u3067Firefox\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u3055\u3052\u305f\u3089\n$ sudo apt-get install firefox=45.0.2+build1-0ubuntu1\n$ sudo apt-mark hold firefox\n\n\u3053\u308c\u3067\u3084\u3063\u3068\u672c\u3068\u540c\u3058\u7d50\u679c\u304c\u8868\u793a\u3055\u308c\u305f\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 10, in <module>\n    assert 'Django' in browser.title\nAssertionError\n\nDjango\u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3092\u4f5c\u6210\u3057\u3066\u3001\u8d77\u52d5\u3059\u308b\u3068\u3002\n$ django-admin.py startproject superlists\n\n$ python3 manage.py runserver\n\n$ python3 functional_tests.py\n$\n\n\u30c6\u30b9\u30c8\u306f\u554f\u984c\u306a\u304f\u7d42\u4e86\u3002\n\u8272\u3005\u4e2d\u9014\u534a\u7aef\u306b\u3057\u3066\u308b\u306e\u306b\u3001\u65b0\u3057\u3044\u3053\u3068\u3092\u59cb\u3081\u308b\u306e\u3082\u3069\u3046\u304b\u3068\u601d\u304a\u3046\u304c\u3001Django\u3068TDD\u304c\u540c\u6642\u306b\u52c9\u5f37\u3067\u304d\u308b\u304a\u5f97\u306a\u672c\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u5b9f\u969b\u306b\u3084\u3063\u3066\u307f\u308b\u3053\u3068\u306b\u3057\u305f\u3002\n\n\n[Test-Driven Development with Python](http://www.obeythetestinggoat.com/pages/book.html)\n\n[Cloudn](http://www.cloudn-service.com/)\u306b\u65b0\u3057\u3044Ubuntu\u306evm\u3092\u7acb\u3063\u3066\u3002\n\u74b0\u5883\u3092\u6e96\u5099\u3002\n\n```shell\n$ sudo apt-get update\n\n$ sudo apt-get upgrade\n\n$ sudo apt install python3-venv python3-pip\n\n$ pip install -U selenium\n```\n\n```shell\n$ vim functional_tests.py\n```\n\n\n```py3\nfrom selenium import webdriver\n\nbrowser = webdriver.Firefox()\nbrowser.get('http://localhost:8000')\n\nassert 'Django' in browser.title\n```\n\u6700\u521d\u306e\u30c6\u30b9\u30c8 functional_tests.py\u3092\u5b9f\u884c\u3057\u305f\u3002\n\u672c\u3060\u3068\u6b21\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u306b\u306a\u308b\u306f\u305a\u3060\u304c\n\n```shell-session\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 6, in <module>\n    assert 'Django' in browser.title\nAssertionError\n```\n\n\u5b9f\u969b\u306e\u30a8\u30e9\u30fc\u306f\u3053\u3093\u306a\u611f\u3058\u3001\u3044\u304d\u306a\u308a\u672c\u306e\u5185\u5bb9\u3068\u9055\u3046\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3002\nX\u304c\u5165\u3063\u3066\u3044\u306a\u3044\u304b\u3089\u5f53\u7136\u304b\n\n```shell-session\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 3, in <module>\n    browser = webdriver.Firefox()\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py\", line 80, in __init__\n    self.binary, timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 52, in __init__\n    self.binary.launch_browser(self.profile, timeout=timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 68, in launch_browser\n    self._wait_until_connectable(timeout=timeout)\n  File \"/home/ubuntu/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 99, in _wait_until_connectable\n    \"The browser appears to have exited \"\nselenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.\n```\n\n\u89e3\u6c7a\u3059\u308b\u305f\u3081\u306bXvfb \u3068 pyvirtualdisplay\u3000\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n```shell\n$ sudo apt-get install xvfb\n$ sudo pip install pyvirtualdisplay\n```\n\n\u3055\u3089\u306b\u3001\u4eca\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306e\u3060\u3068\u30a8\u30e9\u30fc\u306b\u306a\u308b\u3088\u3046\u306a\u306e\u3067Firefox\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u3055\u3052\u305f\u3089\n\n```shell\n$ sudo apt-get install firefox=45.0.2+build1-0ubuntu1\n$ sudo apt-mark hold firefox\n```\n\n\u3053\u308c\u3067\u3084\u3063\u3068\u672c\u3068\u540c\u3058\u7d50\u679c\u304c\u8868\u793a\u3055\u308c\u305f\n\n```shell\n$ python3 functional_tests.py\nTraceback (most recent call last):\n  File \"functional_tests.py\", line 10, in <module>\n    assert 'Django' in browser.title\nAssertionError\n```\n\nDjango\u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3092\u4f5c\u6210\u3057\u3066\u3001\u8d77\u52d5\u3059\u308b\u3068\u3002\n\n```shell\n$ django-admin.py startproject superlists\n\n$ python3 manage.py runserver\n\n$ python3 functional_tests.py\n$\n```\n\n\u30c6\u30b9\u30c8\u306f\u554f\u984c\u306a\u304f\u7d42\u4e86\u3002\n", "tags": ["python3", "Django", "Cloudn"]}