{"context": "\n\ntl; dr\n\n\nctrutil disabled\u3067/bin/pip\u3092\u5b9f\u884c\u3067\u304d\u308b\u3088\u3046\u306b\u3057\u305f\n\nzlib\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u305f\n\nLDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pyenv install 3.5.1\u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n\n\u767a\u751f\u3057\u305f\u8ab2\u984c\n\n\npip install --upgrade pip\u304c\u4f7f\u3048\u306a\u3044\npyenv\u3067python3.5.1\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u306a\u3044\n\n\n\u3084\u3063\u3066\u307f\u305f\u3053\u3068\npython -m pip install --upgrade --force-reinstall pip\n\u3067\u5f37\u5236\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u3066\u307f\u3088\u3046\u3068\u3057\u305f\u304c\u3001\nCollecting pip\n  Using cached pip-9.0.0-py2.py3-none-any.whl\nInstalling collected packages: pip\n  Found existing installation: pip 7.1.2\n    Uninstalling pip-7.1.2:\nException:\nTraceback (most recent call last):\n  File \"/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/shutil.py\", line 538, in move\n    os.rename(src, real_dst)\nPermissionError: [Errno 13] Permission denied: '/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/pip-7.1.2.dist-info/DESCRIPTION.rst' -> '/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/pip-3wy6zsy1-uninstall/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/pip-7.1.2.dist-info/DESCRIPTION.rst'\n\n\u3068\u3067\u3066\u3057\u307e\u3063\u305f\u3002sudo\u3068\u3084\u3063\u3066\u3057\u307e\u3063\u3066\u3082/bin/pip\u3078\u306e\u6a29\u9650\u304c\u7121\u3044\u3068\u6012\u3089\u308c\u308b\u59cb\u672b\u3002\n\u3053\u308c\u306fmac\u306eSIP\u306e\u305b\u3044\u306a\u306e\u3067\u3001\u4e0b\u8a18\u3092\u53c2\u8003\u306bdisabled\u306b\u3002\nhttp://berukann.hatenablog.jp/entry/2015/12/30/123020\n\u518d\u8d77\u52d5\u3057\u3066\u5b9f\u884c\u3057\u3066\u307f\u305f\u3068\u3053\u308d\u3001\nCollecting pip\n  Downloading pip-9.0.0-py2.py3-none-any.whl (1.3MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 1.3MB 278kB/s\nInstalling collected packages: pip\n  Found existing installation: pip 7.1.2\n    Uninstalling pip-7.1.2:\n      Successfully uninstalled pip-7.1.2\nSuccessfully installed pip\n\n\u3068\u3067\u3066\u3044\u308b\u306e\u306b\n$ pip install percol\npyenv: pip: command not found\n\npip\u306f\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3055\u308c\u3066\u304a\u3089\u305a\u3002\u3002\n\u4ed5\u65b9\u306a\u3044\u306e\u3067pyenv\u3067python\u3092\u518d\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u307f\u3088\u3046\u3068\u8a66\u307f\u308b\u304c\u3001\n\nLast 10 log lines:\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__main__.py\", line 4, in <module>\n    ensurepip._main()\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 209, in _main\n    default_pip=args.default_pip,\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 116, in bootstrap\n    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 40, in _run_pip\n    import pip\nzipimport.ZipImportError: can't decompress data; zlib not available\nmake: *** [install] Error 1\n\n\u3068\u51fa\u3066\u3057\u307e\u3063\u305f\u3002\nzlib\u3092\u5165\u308c\u3066\u307f\u308b\u3068\n$ brew update zlib\n\n....\n\nThis formula was found in a tap:\nhomebrew/dupes/zlib\nTo install it, run:\n  brew install homebrew/dupes/zlib\n\n\u3068\u306e\u3053\u3068\u306a\u306e\u3067\u30b3\u30de\u30f3\u30c9\u5909\u3048\u3066\u518d\u5b9f\u884c\n$ brew install homebrew/dupes/zlib\n\n...\n\nThis formula is keg-only, which means it was not symlinked into /usr/local.\n\nmacOS already provides this software and installing another version in\nparallel can cause all kinds of trouble.\n\nGenerally there are no consequences of this for you. If you build your\nown software and it requires this formula, you'll need to add to your\nbuild variables:\n\n    LDFLAGS:  -L/usr/local/opt/zlib/lib\n    CPPFLAGS: -I/usr/local/opt/zlib/include\n    PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig\n\n\u4f55\u3084\u3089\u3042\u3084\u3057\u3044\u30d1\u30e9\u30e1\u30fc\u30bf\u304c\u3002\u3002\n\u3053\u308c\u3092\u6307\u5b9a\u3057\u3066\u307f\u308b\n$ LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pyenv install 3.5.1\n\nDownloading Python-3.5.1.tgz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz\nInstalling Python-3.5.1...\nWARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?\nInstalled Python-3.5.1 to /Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1\n\n\u304a\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u51fa\u6765\u3066\u3044\u308b\u3002\n$ pip -V\npip 7.1.2 from /Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages (python 3.5)\n\npip\u3082\u7121\u4e8b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u305f\ud83d\ude4c\n\n## tl; dr\n\n- `ctrutil disabled`\u3067/bin/pip\u3092\u5b9f\u884c\u3067\u304d\u308b\u3088\u3046\u306b\u3057\u305f\n- `zlib`\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u305f\n- `LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pyenv install 3.5.1`\u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n## \u767a\u751f\u3057\u305f\u8ab2\u984c\n\n- `pip install --upgrade pip`\u304c\u4f7f\u3048\u306a\u3044\n- pyenv\u3067python3.5.1\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u306a\u3044\n\n## \u3084\u3063\u3066\u307f\u305f\u3053\u3068\n\n`python -m pip install --upgrade --force-reinstall pip`\n\u3067\u5f37\u5236\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u3066\u307f\u3088\u3046\u3068\u3057\u305f\u304c\u3001\n\n```bash\nCollecting pip\n  Using cached pip-9.0.0-py2.py3-none-any.whl\nInstalling collected packages: pip\n  Found existing installation: pip 7.1.2\n    Uninstalling pip-7.1.2:\nException:\nTraceback (most recent call last):\n  File \"/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/shutil.py\", line 538, in move\n    os.rename(src, real_dst)\nPermissionError: [Errno 13] Permission denied: '/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/pip-7.1.2.dist-info/DESCRIPTION.rst' -> '/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/pip-3wy6zsy1-uninstall/Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/pip-7.1.2.dist-info/DESCRIPTION.rst'\n```\n\n\u3068\u3067\u3066\u3057\u307e\u3063\u305f\u3002`sudo`\u3068\u3084\u3063\u3066\u3057\u307e\u3063\u3066\u3082`/bin/pip`\u3078\u306e\u6a29\u9650\u304c\u7121\u3044\u3068\u6012\u3089\u308c\u308b\u59cb\u672b\u3002\n\n\u3053\u308c\u306fmac\u306eSIP\u306e\u305b\u3044\u306a\u306e\u3067\u3001\u4e0b\u8a18\u3092\u53c2\u8003\u306bdisabled\u306b\u3002\nhttp://berukann.hatenablog.jp/entry/2015/12/30/123020\n\n\u518d\u8d77\u52d5\u3057\u3066\u5b9f\u884c\u3057\u3066\u307f\u305f\u3068\u3053\u308d\u3001\n\n```bash\nCollecting pip\n  Downloading pip-9.0.0-py2.py3-none-any.whl (1.3MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 1.3MB 278kB/s\nInstalling collected packages: pip\n  Found existing installation: pip 7.1.2\n    Uninstalling pip-7.1.2:\n      Successfully uninstalled pip-7.1.2\nSuccessfully installed pip\n```\n\u3068\u3067\u3066\u3044\u308b\u306e\u306b\n\n```bash\n$ pip install percol\npyenv: pip: command not found\n```\n\npip\u306f\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3055\u308c\u3066\u304a\u3089\u305a\u3002\u3002\n\n\u4ed5\u65b9\u306a\u3044\u306e\u3067pyenv\u3067python\u3092\u518d\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u307f\u3088\u3046\u3068\u8a66\u307f\u308b\u304c\u3001\n\n```bash\n\nLast 10 log lines:\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__main__.py\", line 4, in <module>\n    ensurepip._main()\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 209, in _main\n    default_pip=args.default_pip,\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 116, in bootstrap\n    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)\n  File \"/private/var/folders/qf/q28hqmj54hnb054fj97rwcl40000gn/T/python-build.20161105190035.4540/Python-3.5.1/Lib/ensurepip/__init__.py\", line 40, in _run_pip\n    import pip\nzipimport.ZipImportError: can't decompress data; zlib not available\nmake: *** [install] Error 1\n```\n\n\u3068\u51fa\u3066\u3057\u307e\u3063\u305f\u3002\n\nzlib\u3092\u5165\u308c\u3066\u307f\u308b\u3068\n\n```bash\n$ brew update zlib\n\n....\n\nThis formula was found in a tap:\nhomebrew/dupes/zlib\nTo install it, run:\n  brew install homebrew/dupes/zlib\n```\n\n\u3068\u306e\u3053\u3068\u306a\u306e\u3067\u30b3\u30de\u30f3\u30c9\u5909\u3048\u3066\u518d\u5b9f\u884c\n\n```bash\n$ brew install homebrew/dupes/zlib\n\n...\n\nThis formula is keg-only, which means it was not symlinked into /usr/local.\n\nmacOS already provides this software and installing another version in\nparallel can cause all kinds of trouble.\n\nGenerally there are no consequences of this for you. If you build your\nown software and it requires this formula, you'll need to add to your\nbuild variables:\n\n    LDFLAGS:  -L/usr/local/opt/zlib/lib\n    CPPFLAGS: -I/usr/local/opt/zlib/include\n    PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig\n```\n\n\u4f55\u3084\u3089\u3042\u3084\u3057\u3044\u30d1\u30e9\u30e1\u30fc\u30bf\u304c\u3002\u3002\n\n\u3053\u308c\u3092\u6307\u5b9a\u3057\u3066\u307f\u308b\n\n```bash\n$ LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pyenv install 3.5.1\n\nDownloading Python-3.5.1.tgz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz\nInstalling Python-3.5.1...\nWARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?\nInstalled Python-3.5.1 to /Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1\n```\n\n\u304a\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u51fa\u6765\u3066\u3044\u308b\u3002\n\n```bash\n$ pip -V\npip 7.1.2 from /Users/kotamat/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages (python 3.5)\n```\n\npip\u3082\u7121\u4e8b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u305f\ud83d\ude4c\n", "tags": ["macos", "pyenv", "Python"]}