{"context": "\n\nChainer\u306f\u5165\u308b\u3051\u3069\uff0cimport cupy\u3059\u308b\u3068\u30a8\u30e9\u30fc\u304c\u51fa\u308b\nLinux\u74b0\u5883\u4e0b\u306b\uff0cCUDA-7.5\u3092\u5165\u308c\u305f\u306e\u3061\uff0c\ngcc 8.4.5\uff0cpip\u3092\u4f7f\u3063\u3066\uff0c\n\n$ pip install chainer\n\n\u3059\u308b\u3068\uff0c\n$ Successfully installed chainer-1.20.0.1\n\n\u3068\u51fa\u308b\u306e\u306b\uff0c\u3044\u3056cupy\u3092\u8aad\u307f\u8fbc\u3082\u3046\u3068import cupy\u3059\u308b\u3068\u6b63\u5e38\u306b\u8aad\u307f\u8fbc\u3081\u306a\u3044\uff0e\nTraceback (most recent call last):\n  File \"./train_mnist.py\", line 107, in <module>\n    main()\n  File \"./train_mnist.py\", line 56, in main\n    chainer.cuda.get_device(args.gpu).use()  # Make a specified GPU current\n  File \"C:\\Program Files\\Anaconda3\\lib\\site-packages\\chainer\\cuda.py\", line 167, in get_device\n    check_cuda_available()\n  File \"C:\\Program Files\\Anaconda3\\lib\\site-packages\\chainer\\cuda.py\", line 85, in check_cuda_available\nraise RuntimeError(msg)\nRuntimeError: CUDA environment is not correctly set up\n(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.\n\n\u3046\u301c\u3093\uff0c\u4ed5\u65b9\u304c\u306a\u3044\u306e\u3067\uff0c\n$ pip uninstall chainer\n$ pip install chainer --no-cache-dir -vvvv\n\n\u3068\u3059\u308b\u3068\uff0cCUDA\u306f\u30b9\u30ad\u30c3\u30d7\u3057\u3066\u307e\u3059\u306e\u6587\u5b57\u304c\uff0e\n/usr/bin/ld: cannot find -lcuda\ncollect2: error: ld returned 1 exit status\nCannot build a stub file.\nOriginal error: command 'g++' failed with exit status 1\n**************************************************\n*** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'nvToolsExt']\n*** WARNING: Skip installing cuda support\n*** WARNING: Check your LDFLAGS environment variable\n**************************************************\nInclude directories: ['/usr/local/cuda/include']\nLibrary directories: ['/usr/local/cuda/lib64', '/usr/local/cuda/lib']\n\n\u3068\u3053\u308d\u304c\uff0cLDFLAGS\u3092\u898b\u3066\u3082\u5909\u3067\u306f\u306a\u3044\u306e\u3067\uff0c\u306a\u305c\u3060\u308d\u3046\u3068\u683c\u95d8\u3059\u308b\u3082\u30fb\u30fb\u30fb\u5165\u3089\u306a\u3044\uff0e\n\u3088\u301c\u304f\u30a8\u30e9\u30fc\u3092\u898b\u308b\u3068\uff0c\u305d\u306e\u4e0a\u306e\u3042\u305f\u308a\u3067libcuda.so\u304c\u306a\u3044\u3068\u8a00\u308f\u308c\u3066\u3044\u308b\uff0e\n/usr/bin/ld: cannot find -lcuda\n\n\u307e\u3055\u304b\u3068\u601d\u3063\u3066\uff0c/usr/local/cuda/lib64\u3068/usr/local/cuda/lib\u3092\u898b\u306b\u884c\u304f\u3068\u30fb\u30fb\u30fb\u306a\u3044\uff01\n\u63a2\u3057\u305f\u3068\u3053\u308d\uff0c\u307e\u3055\u304b\u306e/usr/local/cuda/lib64/stubs\u306b\u3044\u3089\u3063\u3057\u3083\u308b\uff0e\n\u305d\u3053\u3067\uff0c\u30d3\u30eb\u30c9\u6642\u306bgcc\u304c\u898b\u306b\u884c\u304fLIBRARY_PATH\u306b\u3053\u306e\u30d5\u30a9\u30eb\u30c0\u3092\u901a\u3057\u3066\u3084\u308b\uff0e\n$ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64\n$ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib\n$ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64/stubs\n\n\u305d\u308c\u3067\u518d\u3073\n$ pip install chainer --no-cache-dir -vvvv\n\n\u3059\u308b\u3068\uff0cWARNING\u304c\u51fa\u306a\u304f\u306a\u3063\u305f\u305e\uff01\uff01\uff01\uff01\n\n\u3057\u304b\u3057\u305d\u306e\u307e\u307e\u3060\u3068\u8db3\u308a\u306a\u3044\n\u3068\u3053\u308d\u304c\uff0c\u4e07\u3092\u8f9e\u3057\u3066cupy\u3092\u8aad\u307f\u8fbc\u3080\u3068\uff0c\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/__init__.py\", line 18, in <module>\n    raise six.reraise(RuntimeError, RuntimeError(msg), exc_info[2])\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/__init__.py\", line 7, in <module>\n    from cupy import core  # NOQA\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/core/__init__.py\", line 1, in <module>\n    from cupy.core import core  # NOQA\nRuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.\n\noriginal error: libcuda.so.1: cannot open shared object file: No such file or directory\n\n\u307e\u305f\u6012\u3089\u308c\u308b\uff0elibcuda.so.1\u304c\u306a\u3044\u3089\u3057\u3044\uff0e\u691c\u7d22\u3057\u3066\u3082\u78ba\u304b\u306b\u306a\u3044\uff0e\u305d\u3053\u3067\uff0clibcuda.so\u304b\u3089\u30b7\u30f3\u30dc\u30ea\u30c3\u30af\u30ea\u30f3\u30af\u3092\u8cbc\u3063\u3066\u3084\u308b\u3053\u3068\u306b\u3059\u308b\uff0e\n$ cd /usr/local/cuda/lib64/stubs/\n$ ln -s libcuda.so libcuda.so.1\n\n\u3067\uff0c\u5148\u307b\u3069\u3068\u540c\u3058\u3088\u3046\u306b\uff0c\u3053\u308c\u306e\u30c7\u30a3\u30ec\u30af\u30c8\u30ea\u3092\u5b9f\u884c\u6642\u306b\u30e9\u30a4\u30d6\u30e9\u30ea\u3092\u8aad\u307f\u8fbc\u3080LD_LIBRARY_PATH\u306b\u901a\u3057\u3066\u3084\u308b\uff0e\n$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64\n$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib\n$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs\n\n\u3053\u308c\u3067\uff0cimport cupy\u3059\u308b\u3068\u30fb\u30fb\u30fb\u3067\u304d\u305f\uff01\uff01\uff01\u3067\u304d\u305f\uff01\uff01\uff01\uff01\n#Chainer\u306f\u5165\u308b\u3051\u3069\uff0cimport cupy\u3059\u308b\u3068\u30a8\u30e9\u30fc\u304c\u51fa\u308b\nLinux\u74b0\u5883\u4e0b\u306b\uff0cCUDA-7.5\u3092\u5165\u308c\u305f\u306e\u3061\uff0c\ngcc 8.4.5\uff0cpip\u3092\u4f7f\u3063\u3066\uff0c\n```\n$ pip install chainer\n```\n\u3059\u308b\u3068\uff0c\n\n```\n$ Successfully installed chainer-1.20.0.1\n```\n\u3068\u51fa\u308b\u306e\u306b\uff0c\u3044\u3056cupy\u3092\u8aad\u307f\u8fbc\u3082\u3046\u3068import cupy\u3059\u308b\u3068\u6b63\u5e38\u306b\u8aad\u307f\u8fbc\u3081\u306a\u3044\uff0e\n\n    Traceback (most recent call last):\n      File \"./train_mnist.py\", line 107, in <module>\n        main()\n      File \"./train_mnist.py\", line 56, in main\n        chainer.cuda.get_device(args.gpu).use()  # Make a specified GPU current\n      File \"C:\\Program Files\\Anaconda3\\lib\\site-packages\\chainer\\cuda.py\", line 167, in get_device\n        check_cuda_available()\n      File \"C:\\Program Files\\Anaconda3\\lib\\site-packages\\chainer\\cuda.py\", line 85, in check_cuda_available\n    raise RuntimeError(msg)\n    RuntimeError: CUDA environment is not correctly set up\n    (see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.\n\n\n\u3046\u301c\u3093\uff0c\u4ed5\u65b9\u304c\u306a\u3044\u306e\u3067\uff0c\n\n```\n$ pip uninstall chainer\n$ pip install chainer --no-cache-dir -vvvv\n```\n\n\u3068\u3059\u308b\u3068\uff0cCUDA\u306f\u30b9\u30ad\u30c3\u30d7\u3057\u3066\u307e\u3059\u306e\u6587\u5b57\u304c\uff0e\n\n    /usr/bin/ld: cannot find -lcuda\n    collect2: error: ld returned 1 exit status\n    Cannot build a stub file.\n    Original error: command 'g++' failed with exit status 1\n    **************************************************\n    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'nvToolsExt']\n    *** WARNING: Skip installing cuda support\n    *** WARNING: Check your LDFLAGS environment variable\n    **************************************************\n    Include directories: ['/usr/local/cuda/include']\n    Library directories: ['/usr/local/cuda/lib64', '/usr/local/cuda/lib']\n\n\n\u3068\u3053\u308d\u304c\uff0cLDFLAGS\u3092\u898b\u3066\u3082\u5909\u3067\u306f\u306a\u3044\u306e\u3067\uff0c\u306a\u305c\u3060\u308d\u3046\u3068\u683c\u95d8\u3059\u308b\u3082\u30fb\u30fb\u30fb\u5165\u3089\u306a\u3044\uff0e\n\u3088\u301c\u304f\u30a8\u30e9\u30fc\u3092\u898b\u308b\u3068\uff0c\u305d\u306e\u4e0a\u306e\u3042\u305f\u308a\u3067libcuda.so\u304c\u306a\u3044\u3068\u8a00\u308f\u308c\u3066\u3044\u308b\uff0e\n\n    /usr/bin/ld: cannot find -lcuda\n\n\u307e\u3055\u304b\u3068\u601d\u3063\u3066\uff0c/usr/local/cuda/lib64\u3068/usr/local/cuda/lib\u3092\u898b\u306b\u884c\u304f\u3068\u30fb\u30fb\u30fb\u306a\u3044\uff01\n\u63a2\u3057\u305f\u3068\u3053\u308d\uff0c\u307e\u3055\u304b\u306e/usr/local/cuda/lib64/stubs\u306b\u3044\u3089\u3063\u3057\u3083\u308b\uff0e\n\u305d\u3053\u3067\uff0c\u30d3\u30eb\u30c9\u6642\u306bgcc\u304c\u898b\u306b\u884c\u304fLIBRARY_PATH\u306b\u3053\u306e\u30d5\u30a9\u30eb\u30c0\u3092\u901a\u3057\u3066\u3084\u308b\uff0e\n\n    $ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64\n    $ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib\n    $ export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64/stubs\n\n\u305d\u308c\u3067\u518d\u3073\n\n    $ pip install chainer --no-cache-dir -vvvv\n\n\u3059\u308b\u3068\uff0cWARNING\u304c\u51fa\u306a\u304f\u306a\u3063\u305f\u305e\uff01\uff01\uff01\uff01\n\n#\u3057\u304b\u3057\u305d\u306e\u307e\u307e\u3060\u3068\u8db3\u308a\u306a\u3044\n\u3068\u3053\u308d\u304c\uff0c\u4e07\u3092\u8f9e\u3057\u3066cupy\u3092\u8aad\u307f\u8fbc\u3080\u3068\uff0c\n\n```\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/__init__.py\", line 18, in <module>\n    raise six.reraise(RuntimeError, RuntimeError(msg), exc_info[2])\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/__init__.py\", line 7, in <module>\n    from cupy import core  # NOQA\n  File \"/home/slab/hirohara/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/cupy/core/__init__.py\", line 1, in <module>\n    from cupy.core import core  # NOQA\nRuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.\n\noriginal error: libcuda.so.1: cannot open shared object file: No such file or directory\n```\n\u307e\u305f\u6012\u3089\u308c\u308b\uff0elibcuda.so.1\u304c\u306a\u3044\u3089\u3057\u3044\uff0e\u691c\u7d22\u3057\u3066\u3082\u78ba\u304b\u306b\u306a\u3044\uff0e\u305d\u3053\u3067\uff0clibcuda.so\u304b\u3089\u30b7\u30f3\u30dc\u30ea\u30c3\u30af\u30ea\u30f3\u30af\u3092\u8cbc\u3063\u3066\u3084\u308b\u3053\u3068\u306b\u3059\u308b\uff0e\n\n    $ cd /usr/local/cuda/lib64/stubs/\n    $ ln -s libcuda.so libcuda.so.1\n\n\u3067\uff0c\u5148\u307b\u3069\u3068\u540c\u3058\u3088\u3046\u306b\uff0c\u3053\u308c\u306e\u30c7\u30a3\u30ec\u30af\u30c8\u30ea\u3092\u5b9f\u884c\u6642\u306b\u30e9\u30a4\u30d6\u30e9\u30ea\u3092\u8aad\u307f\u8fbc\u3080LD_LIBRARY_PATH\u306b\u901a\u3057\u3066\u3084\u308b\uff0e\n\n    $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64\n    $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib\n    $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs\n\n\u3053\u308c\u3067\uff0cimport cupy\u3059\u308b\u3068\u30fb\u30fb\u30fb\u3067\u304d\u305f\uff01\uff01\uff01\u3067\u304d\u305f\uff01\uff01\uff01\uff01\n", "tags": ["Chainer", "CuPy", "gcc4.8"]}