{"context": " More than 1 year has passed since last update.$ git clone git@gitlab.server:user/repo.git\nCloning into 'app'...\n/usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: Name or service not known (SocketError)\n    from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'\n    from /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'\n    from /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'\n    from /usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'\n    from /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'\n    from /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'\n    from /home/git/gitlab-shell/lib/gitlab_net.rb:62:in `get'\n    from /home/git/gitlab-shell/lib/gitlab_net.rb:17:in `allowed?'\n    from /home/git/gitlab-shell/lib/gitlab_shell.rb:59:in `validate_access'\n    from /home/git/gitlab-shell/lib/gitlab_shell.rb:23:in `exec'\n    from /home/git/gitlab-shell/bin/gitlab-shell:16:in `<main>'\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n$ \n\n\u21d2GitLab\u3092\u8a2d\u7f6e\u3057\u3066\u308b\u30b5\u30fc\u30d0\u30fc\u306ehosts\u8a2d\u5b9a\u3092\u4fee\u6b63\u3059\u308c\u3070\u3044\u3051\u305f\u30fb\u03c9\u30fb\uff01\n127.0.0.1 gitlab.server\n\n\u5fd8\u308c\u3066\u305f\u30fb\u03c9\u30fb\uff40\n\u3061\u306a\u307f\u306bgitlab-shell\u306econfig.yml\u3067gitlab_url\u306e\u6700\u5f8c\u306e/\u304c\u5165\u3063\u3066\u3044\u306a\u3044\u5834\u5408\u306b\u3082\u540c\u3058\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u3067\u308b\u307f\u305f\u3044\u3067\u3059\u3002\n\nconfig.yml\ngitlab_url:\"http://gitlab.server/\"\n\n\n\u53c2\u8003\uff1ahttps://github.com/gitlabhq/gitlab-shell/issues/17\n\n```\n$ git clone git@gitlab.server:user/repo.git\nCloning into 'app'...\n/usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: Name or service not known (SocketError)\n\tfrom /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'\n\tfrom /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'\n\tfrom /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'\n\tfrom /usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'\n\tfrom /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'\n\tfrom /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'\n\tfrom /home/git/gitlab-shell/lib/gitlab_net.rb:62:in `get'\n\tfrom /home/git/gitlab-shell/lib/gitlab_net.rb:17:in `allowed?'\n\tfrom /home/git/gitlab-shell/lib/gitlab_shell.rb:59:in `validate_access'\n\tfrom /home/git/gitlab-shell/lib/gitlab_shell.rb:23:in `exec'\n\tfrom /home/git/gitlab-shell/bin/gitlab-shell:16:in `<main>'\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n$ \n```\n\n\u21d2GitLab\u3092\u8a2d\u7f6e\u3057\u3066\u308b\u30b5\u30fc\u30d0\u30fc\u306ehosts\u8a2d\u5b9a\u3092\u4fee\u6b63\u3059\u308c\u3070\u3044\u3051\u305f\u30fb\u03c9\u30fb\uff01\n\n``` /etc/hosts\n127.0.0.1 gitlab.server\n```\n\n\u5fd8\u308c\u3066\u305f\u30fb\u03c9\u30fb\uff40\n\n\u3061\u306a\u307f\u306b`gitlab-shell`\u306econfig.yml\u3067gitlab_url\u306e\u6700\u5f8c\u306e`/`\u304c\u5165\u3063\u3066\u3044\u306a\u3044\u5834\u5408\u306b\u3082\u540c\u3058\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u3067\u308b\u307f\u305f\u3044\u3067\u3059\u3002\n\n```config.yml\ngitlab_url:\"http://gitlab.server/\"\n```\n\n\n\u53c2\u8003\uff1a[https://github.com/gitlabhq/gitlab-shell/issues/17](https://github.com/gitlabhq/gitlab-shell/issues/17)\n", "tags": ["GitLab", "error"]}