{"tags": ["Erlang"], "context": " More than 1 year has passed since last update.erlang:error/1\u3092\u4f7f\u3063\u3066\u4f8b\u5916(ex. badarg)\u3092\u9001\u51fa\u3059\u308b\u3068\u3001\u88dc\u8db3\u3057\u305f\u5f8c\u306eerlang:get_stacktrace/1\u306e\u7d50\u679c\u306b\u4f8b\u5916\u304c\u767a\u751f\u3057\u305f\u95a2\u6570\u306e\u30a2\u30ea\u30c6\u30a3\u60c5\u5831(\u5f15\u6570\u6570)\u3057\u304b\u8f09\u3063\u3066\u3044\u306a\u304f\u3066\u82e6\u52b4\u3057\u305f\u899a\u3048\u304c\u3042\u308b\u304c\u3001erlang:error/2\u3092\u4f7f\u3048\u3070\u3001\u5f15\u6570\u306e\u5b8c\u5168\u306a\u60c5\u5831\u3092\u8f09\u305b\u308b\u3053\u3068\u304c\u3067\u304d\u308b\u6a21\u69d8\u3002\n\nexception_test.erl\n-module(exception_test).\n\n-export([hoge/1, fuga/1]).\n\n%% @doc erlang:error/1\u3092\u4f7f\u3063\u3066\u4f8b\u5916\u9001\u51fa\nhoge(_Arg) ->\n  error(badarg).\n\n%% @doc erlang:error/2\u3092\u4f7f\u3063\u3066\u4f8b\u5916\u9001\u51fa\nfuga(Arg) ->\n  error(badarg, [Arg]).\n\n\n\nshell\n$ erl\nErlang R16B03-1 (erts-5.10.4) [source] [64-bit]\nEshell V5.10.4  (abort with ^G)\n\n> c(exception_test).\n{ok, exception_test}\n\n%% erlang:error/1\u306e\u5834\u5408\u306e\u30a8\u30e9\u30fc\u8868\u793a\u304a\u3088\u3073\u30b9\u30bf\u30c3\u30af\u30c8\u30ec\u30fc\u30b9\n> exception_test:hoge(erlang).\n** exception error: bad argument\n     in function  exception_test:hoge/1 (exception_test.erl, line 8)\n\n> catch exception_test:hoge(erlang).\n{'EXIT',{badarg,[{exception_test,hoge,1,\n                                 [{file,\"exception_test.erl\"},{line,8}]},\n                 {erl_eval,do_apply,6,[{file,\"erl_eval.erl\"},{line,573}]},\n                 {erl_eval,expr,5,[{file,\"erl_eval.erl\"},{line,357}]},\n                 {shell,exprs,7,[{file,\"shell.erl\"},{line,674}]},\n                 {shell,eval_exprs,7,[{file,\"shell.erl\"},{line,629}]},\n                 {shell,eval_loop,3,[{file,\"shell.erl\"},{line,614}]}]}}\n\n%% erlang:error/2\u306e\u5834\u5408\u306e\u30a8\u30e9\u30fc\u8868\u793a\u304a\u3088\u3073\u30b9\u30bf\u30c3\u30af\u30c8\u30ec\u30fc\u30b9\n> exception_test:fuga(erlang).\n** exception error: bad argument\n     in function  exception_test:fuga/1\n        called as exception_test:fuga(erlang)  % \u5f15\u6570\u60c5\u5831\u304c\u8868\u793a\u3055\u308c\u308b\n\n> catch exception_test:fuga(erlang).\n{'EXIT',{badarg,[{exception_test,fuga,\n                                 [erlang], % \u30a2\u30ea\u30c6\u30a3\u306e\u4ee3\u308f\u308a\u306b\u5f15\u6570\u304c\u53d6\u5f97\u3067\u304d\u308b\n                                 [{file,\"exception_test.erl\"},{line,13}]},\n                 {erl_eval,do_apply,6,[{file,\"erl_eval.erl\"},{line,573}]},\n                 {erl_eval,expr,5,[{file,\"erl_eval.erl\"},{line,357}]},\n                 {shell,exprs,7,[{file,\"shell.erl\"},{line,674}]},\n                 {shell,eval_exprs,7,[{file,\"shell.erl\"},{line,629}]},\n                 {shell,eval_loop,3,[{file,\"shell.erl\"},{line,614}]}]}}\n\n\nerlang:error/1\u3092\u4f7f\u3063\u3066\u4f8b\u5916(ex. badarg)\u3092\u9001\u51fa\u3059\u308b\u3068\u3001\u88dc\u8db3\u3057\u305f\u5f8c\u306eerlang:get_stacktrace/1\u306e\u7d50\u679c\u306b\u4f8b\u5916\u304c\u767a\u751f\u3057\u305f\u95a2\u6570\u306e\u30a2\u30ea\u30c6\u30a3\u60c5\u5831(\u5f15\u6570\u6570)\u3057\u304b\u8f09\u3063\u3066\u3044\u306a\u304f\u3066\u82e6\u52b4\u3057\u305f\u899a\u3048\u304c\u3042\u308b\u304c\u3001erlang:error/2\u3092\u4f7f\u3048\u3070\u3001\u5f15\u6570\u306e\u5b8c\u5168\u306a\u60c5\u5831\u3092\u8f09\u305b\u308b\u3053\u3068\u304c\u3067\u304d\u308b\u6a21\u69d8\u3002\n\n```erlang:exception_test.erl\n-module(exception_test).\n\n-export([hoge/1, fuga/1]).\n\n%% @doc erlang:error/1\u3092\u4f7f\u3063\u3066\u4f8b\u5916\u9001\u51fa\nhoge(_Arg) ->\n  error(badarg).\n\n%% @doc erlang:error/2\u3092\u4f7f\u3063\u3066\u4f8b\u5916\u9001\u51fa\nfuga(Arg) ->\n  error(badarg, [Arg]).\n```\n\n```erlang:shell\n$ erl\nErlang R16B03-1 (erts-5.10.4) [source] [64-bit]\nEshell V5.10.4  (abort with ^G)\n\n> c(exception_test).\n{ok, exception_test}\n\n%% erlang:error/1\u306e\u5834\u5408\u306e\u30a8\u30e9\u30fc\u8868\u793a\u304a\u3088\u3073\u30b9\u30bf\u30c3\u30af\u30c8\u30ec\u30fc\u30b9\n> exception_test:hoge(erlang).\n** exception error: bad argument\n     in function  exception_test:hoge/1 (exception_test.erl, line 8)\n\n> catch exception_test:hoge(erlang).\n{'EXIT',{badarg,[{exception_test,hoge,1,\n                                 [{file,\"exception_test.erl\"},{line,8}]},\n                 {erl_eval,do_apply,6,[{file,\"erl_eval.erl\"},{line,573}]},\n                 {erl_eval,expr,5,[{file,\"erl_eval.erl\"},{line,357}]},\n                 {shell,exprs,7,[{file,\"shell.erl\"},{line,674}]},\n                 {shell,eval_exprs,7,[{file,\"shell.erl\"},{line,629}]},\n                 {shell,eval_loop,3,[{file,\"shell.erl\"},{line,614}]}]}}\n\n%% erlang:error/2\u306e\u5834\u5408\u306e\u30a8\u30e9\u30fc\u8868\u793a\u304a\u3088\u3073\u30b9\u30bf\u30c3\u30af\u30c8\u30ec\u30fc\u30b9\n> exception_test:fuga(erlang).\n** exception error: bad argument\n     in function  exception_test:fuga/1\n        called as exception_test:fuga(erlang)  % \u5f15\u6570\u60c5\u5831\u304c\u8868\u793a\u3055\u308c\u308b\n\n> catch exception_test:fuga(erlang).\n{'EXIT',{badarg,[{exception_test,fuga,\n                                 [erlang], % \u30a2\u30ea\u30c6\u30a3\u306e\u4ee3\u308f\u308a\u306b\u5f15\u6570\u304c\u53d6\u5f97\u3067\u304d\u308b\n                                 [{file,\"exception_test.erl\"},{line,13}]},\n                 {erl_eval,do_apply,6,[{file,\"erl_eval.erl\"},{line,573}]},\n                 {erl_eval,expr,5,[{file,\"erl_eval.erl\"},{line,357}]},\n                 {shell,exprs,7,[{file,\"shell.erl\"},{line,674}]},\n                 {shell,eval_exprs,7,[{file,\"shell.erl\"},{line,629}]},\n                 {shell,eval_loop,3,[{file,\"shell.erl\"},{line,614}]}]}}\n```\n"}