{"context": "\n\n\u7d50\u8ad6\n\u300cv0.11.1.b2095 \u300d\u3092\u4f7f\u3063\u3066\u3044\u308b\u4eba\u306f\u300cv0.12.0.b2449\u300d\u4ee5\u4e0a\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u4f7f\u304a\u3046\n\n\u73fe\u8c61\n\u4e0b\u8a18\u3092\u53c2\u8003\u306bRe:dash\u306e\u5c0e\u5165\u3092\u8a66\u307f\u305f\n\u300cRe:dash\u300d\u3092\u300cDocker for Mac\u300d\u3067\u52d5\u304b\u3057\u3066\u307f\u305f - Qiita\n\u74b0\u5883\u3082\u4e0a\u8a18\u306e\u8a18\u4e8b\u306b\u5408\u308f\u305b\u3066\nv0.11.1.b2095\n\n\u3092\u4f7f\u7528\u3057\u305f\n\u305d\u3046\u3059\u308b\u3068\n$ ./setup/docker/create_database.sh\n\n\u5b9f\u884c\u6642\u306b\u4e0b\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u3066\u3057\u307e\u3063\u305f\nusage: manage.py [-h]\n                 {status,shell,users,database,send_test_mail,runserver,version,groups,org,ds,runworkers,check_settings}\n                 ...\nmanage.py: error: unrecognized arguments: -n -t pg -o {\"user\": \"redash_reader\", \"password\": \"redash_reader\", \"host\": \"postgres\", \"dbname\": \"postgres\"}\n\n\u4f7f\u7528\u306b\u306f\u7279\u306b\u554f\u984c\u306f\u306a\u3044\u3088\u3046\u3060\u3051\u3069\u6c17\u6301\u3061\u304c\u60aa\u304b\u3063\u305f\u306e\u3067\u8abf\u3079\u305f\u3068\u3053\u308d\n\u4e0b\u8a18\u30d7\u30eb\u30ea\u30af\u3067\u4fee\u6b63\u3055\u308c\u3066\u3044\u308b\u3088\u3046\u3060\u3063\u305f\nhttps://github.com/getredash/redash/pull/1170\n\u300cv0.12.0.b2449\u300d\u4ee5\u4e0a\u3092\u4f7f\u7528\u3059\u308b\u3053\u3068\u3067\u89e3\u6c7a\u3057\u305f\n# \u7d50\u8ad6\n\n\u300cv0.11.1.b2095 \u300d\u3092\u4f7f\u3063\u3066\u3044\u308b\u4eba\u306f\u300cv0.12.0.b2449\u300d\u4ee5\u4e0a\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u3092\u4f7f\u304a\u3046\n\n# \u73fe\u8c61\n\n\u4e0b\u8a18\u3092\u53c2\u8003\u306bRe:dash\u306e\u5c0e\u5165\u3092\u8a66\u307f\u305f\n\n[\u300cRe:dash\u300d\u3092\u300cDocker for Mac\u300d\u3067\u52d5\u304b\u3057\u3066\u307f\u305f \\- Qiita](http://qiita.com/tbuchi888/items/275bb2ed341c2936c9c3)\n\n\u74b0\u5883\u3082\u4e0a\u8a18\u306e\u8a18\u4e8b\u306b\u5408\u308f\u305b\u3066\n\n```\nv0.11.1.b2095\n```\n\n\u3092\u4f7f\u7528\u3057\u305f\n\n\u305d\u3046\u3059\u308b\u3068\n\n```\n$ ./setup/docker/create_database.sh\n```\n\n\u5b9f\u884c\u6642\u306b\u4e0b\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u3066\u3057\u307e\u3063\u305f\n\n```\nusage: manage.py [-h]\n                 {status,shell,users,database,send_test_mail,runserver,version,groups,org,ds,runworkers,check_settings}\n                 ...\nmanage.py: error: unrecognized arguments: -n -t pg -o {\"user\": \"redash_reader\", \"password\": \"redash_reader\", \"host\": \"postgres\", \"dbname\": \"postgres\"}\n```\n\n\u4f7f\u7528\u306b\u306f\u7279\u306b\u554f\u984c\u306f\u306a\u3044\u3088\u3046\u3060\u3051\u3069\u6c17\u6301\u3061\u304c\u60aa\u304b\u3063\u305f\u306e\u3067\u8abf\u3079\u305f\u3068\u3053\u308d\n\u4e0b\u8a18\u30d7\u30eb\u30ea\u30af\u3067\u4fee\u6b63\u3055\u308c\u3066\u3044\u308b\u3088\u3046\u3060\u3063\u305f\n\nhttps://github.com/getredash/redash/pull/1170\n\n\u300cv0.12.0.b2449\u300d\u4ee5\u4e0a\u3092\u4f7f\u7528\u3059\u308b\u3053\u3068\u3067\u89e3\u6c7a\u3057\u305f\n", "tags": ["redash"]}